services:
  interface:
    build: interface
    ports:
      - "5000:5000"
    environment:
      API_HOST: http://service:8080
    depends_on:
      - service

  service:
    build: service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/vivida_dev
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

      S3_ENDPOINT: http://172.17.0.1:9000
      S3_BUCKET: vivida-s3-dev
      S3_REGION: ru-central1
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      
      ANALYSIS_ENDPOINT: http://model:5050
    depends_on:
      - db
      - s3
      - model

  model:
    build: model
    ports:
      - "5050:5050"

  db:
    image: postgres:17.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: vivida_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

  s3:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
