spring:
  application:
    name: vivida

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/vivida_dev}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:root}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

minio:
  endpoint: ${S3_ENDPOINT:http://localhost:9000}
  bucket: ${S3_BUCKET:vivida-s3-dev}
  region: ${S3_REGION:ru-central1}

  access-key: ${S3_ACCESS_KEY:minioadmin}
  secret-key: ${S3_SECRET_KEY:minioadmin}

analysis:
  endpoint: ${ANALYSIS_ENDPOINT:http://localhost:5050}